---
- include_vars: "{{ ansible_distribution }}.yml"

- name: install package
  tags: packages,workstation-packages
  package:
    name: "{{packages}}"
    state: latest

- name: Install package (Arch Linux)
  aur:
    use: yay
    state: present
    name:
      - nerd-fonts-complete
      - ttf-gentium-basic
  become: yes
  become_user: aur_builder
  when:
    - ansible_os_family == "Archlinux"
...